trigger:
  tags:
    include:
    - v?.*
pr: none


jobs:
- job: test_manylinux2014
  displayName: 'Manylinux_aarch64_test'
  strategy:
    matrix:
      py36 aarch64:
        python.code: 'cp36-cp36m'
        manylinux: 'manylinux_aarch64'
      py37 aarch64:
        python.code: 'cp37-cp37m'
        manylinux: 'manylinux_aarch64'
      py38 aarch64:
        python.code: 'cp38-cp38'
        manylinux: 'manylinux_aarch644'
      py39 aarch64:
        python.code: 'cp39-cp39'
        manylinux: 'manylinux_aarch64'
  pool:
    vmImage: 'ubuntu-latest'
 
  steps:
  - checkout: self
    submodules: true
    clean: true
    
  - script: docker run --rm --privileged hypriot/qemu-register
    displayName: 'Registering qemu'
  - script: |
      set -xeo pipefail
      docker run -v $(pwd):"${DOCKER_ROOT_DIRECTORY}":rw,z \
                 -e HOST_USER_ID \
                 "quay.io/pypa/manylinux2014_aarch64" \
                 bash -c "cd $DOCKER_ROOT_DIRECTORY;
                 /opt/python/$(python.code)/bin/python -m venv .build-venv && \
                 source .build-venv/bin/activate && \
                 pip install --upgrade pip setuptools wheel pytest && \
                 pip --version && \
                 pip install numpy==1.19.4 pandas==1.1.4 psutil scipy joblib && \
                 cd python-package && python setup.py install && \
                 cd .. && python -m pytest tests/;"
    displayName: 'Running aarch64 wheel test'
    env:
      DOCKER_ROOT_DIRECTORY: "/home/source_root/"
      HOST_USER_ID: $(id -u)
