stages:
- stage: test
  displayName: 'Run tests'

  jobs:
  - job:
    strategy:
      matrix:
        Py35-C-Linux:
          python.version: '3.5'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py36-C-Linux:
          python.version: '3.6'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py37-C-Linux:
          python.version: '3.7'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py38-C-Linux:
          python.version: '3.8'
          no_extensions: ''
          image: 'ubuntu-latest'
        
    pool:
      vmImage: '$(image)'

    timeoutInMinutes: 10

    steps:
    - checkout: self
      clean: true
      submodules: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip setuptools wheel
      displayName: 'Update pip'
    - script: |
        cd python-package && python setup.py install
      displayName: 'Install itself'
    - script: |
        python setup.py bdist_wheel
      displayName: 'build  wheel'
    - script: |
        python -m pip install pytest-azurepipelines
      displayName: 'Install pytest-azurepipelines'
    - script: |
        python -m pytest tests -vv
      displayName: 'pytest'
